# Generated by Django 5.2.1 on 2025-06-01 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0020_chatfluxoopcao_fluxo_destino"),
    ]

    operations = [
        migrations.AddField(
            model_name="pedido",
            name="observacao",
            field=models.TextField(blank=True, default=" ", null=True),
        ),
    ]
