# Generated by Django 5.2.1 on 2025-06-01 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0021_pedido_observacao"),
    ]

    operations = [
        migrations.AddField(
            model_name="partesproduto",
            name="maximo",
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name="partesproduto",
            name="minimo",
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name="partesproduto",
            name="obrigatorio",
            field=models.BooleanField(default=True),
        ),
    ]
