# Generated by Django 5.2.1 on 2025-06-02 00:31

import django.db.models.deletion
import shortuuid.django_fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0022_partesproduto_maximo_partesproduto_minimo_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="pedidoitems",
            options={
                "ordering": ["-data_criacao"],
                "verbose_name": "Item do Pedido",
                "verbose_name_plural": "Itens do Pedido",
            },
        ),
        migrations.RemoveField(
            model_name="pedido",
            name="observacao",
        ),
        migrations.RemoveField(
            model_name="pedidoitems",
            name="partes_produto",
        ),
        migrations.AddField(
            model_name="pedido",
            name="observacao_geral",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pedidoitems",
            name="observacao",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="partesproduto",
            name="codigo",
            field=shortuuid.django_fields.ShortUUIDField(
                alphabet="abcdefg1234",
                editable=False,
                length=7,
                max_length=9,
                prefix="pp",
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="partesproduto",
            name="imagem",
            field=models.ImageField(
                max_length=400, upload_to="get_path_partes_produto_imagem"
            ),
        ),
        migrations.AlterField(
            model_name="partesproduto",
            name="maximo",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="partesproduto",
            name="minimo",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="partesproduto",
            name="obrigatorio",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="pedido",
            name="cliente",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="pedido",
            name="items",
            field=models.ManyToManyField(
                blank=True, related_name="pedidos", to="core.pedidoitems"
            ),
        ),
        migrations.AlterField(
            model_name="pedido",
            name="status",
            field=models.CharField(
                choices=[
                    ("P", "Pendente"),
                    ("A", "Aprovado"),
                    ("R", "Rejeitado"),
                    ("C", "Cancelado"),
                    ("E", "Enviado"),
                    ("F", "Finalizado"),
                ],
                default="P",
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="pedidoitems",
            name="codigo",
            field=shortuuid.django_fields.ShortUUIDField(
                alphabet="abcdefg1234",
                editable=False,
                length=7,
                max_length=9,
                prefix="it",
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="produto",
            name="imagem",
            field=models.ImageField(
                max_length=400, upload_to="get_path_produto_imagem"
            ),
        ),
        migrations.AlterField(
            model_name="produto",
            name="partes",
            field=models.ManyToManyField(
                blank=True, related_name="produtos_associados", to="core.partesproduto"
            ),
        ),
        migrations.CreateModel(
            name="PedidoItemParte",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantidade", models.PositiveIntegerField(default=1)),
                (
                    "parte_produto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.partesproduto",
                    ),
                ),
                (
                    "pedido_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="configuracao_partes",
                        to="core.pedidoitems",
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuração de Parte do Item",
                "verbose_name_plural": "Configurações de Partes dos Itens",
                "unique_together": {("pedido_item", "parte_produto")},
            },
        ),
        migrations.AddField(
            model_name="pedidoitems",
            name="partes_selecionadas",
            field=models.ManyToManyField(
                blank=True,
                through="core.PedidoItemParte",
                through_fields=("pedido_item", "parte_produto"),
                to="core.partesproduto",
            ),
        ),
    ]
