# Generated by Django 5.2.1 on 2025-06-08 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0023_alter_pedidoitems_options_remove_pedido_observacao_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="partesproduto",
            name="imagem",
            field=models.ImageField(
                max_length=400, null=True, upload_to="get_path_partes_produto_imagem"
            ),
        ),
        migrations.AlterField(
            model_name="pedido",
            name="status",
            field=models.CharField(
                choices=[
                    ("P", "Pendente"),
                    ("A", "Produção"),
                    ("R", "Rejeitado"),
                    ("C", "Cancelado"),
                    ("E", "Enviado"),
                    ("F", "Finalizado"),
                ],
                default="P",
                max_length=1,
            ),
        ),
    ]
