# Generated by Django 5.2.1 on 2025-06-08 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0024_alter_partesproduto_imagem_alter_pedido_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="produto",
            name="imagem",
            field=models.ImageField(
                max_length=400, null=True, upload_to="get_path_produto_imagem"
            ),
        ),
    ]
